language: objective-c
osx_image: xcode8.3
podfile: Example/Podfile

before_install:
    - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
    - set -o pipefail && xcodebuild test -project Marker/Marker.xcodeproj -scheme Marker-iOS -destination 'name=iPhone 7,OS=10.3.1' | xcpretty
    - set -o pipefail && xcodebuild test -project Marker/Marker.xcodeproj -scheme Marker-macOS -destination 'arch=x86_64' | xcpretty
    - set -o pipefail && xcodebuild test -project Marker/Marker.xcodeproj -scheme Marker-tvOS -destination 'name=Apple TV 1080p,OS=10.2' | xcpretty
    - pod lib lint 
