language: objective-c
osx_image: xcode8.3
podfile: Example/Podfile

before_install:
    - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
    - set -o pipefail && xcodebuild test -project Marker/Marker.xcodeproj -scheme Marker -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' | xcpretty
    - pod lib lint 
