language: objective-c
osx_image: xcode8
podfile: Example/Podfile

script:
- set -o pipefail && xcodebuild test -workspace Example/Marker.xcworkspace -scheme Marker-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
