language: objective-c
osx_image: xcode8
podfile: Example/Podfile

before_install:
    - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
    - set -o pipefail && xcodebuild test -workspace Example/Marker.xcworkspace -scheme Marker-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty
    - pod lib lint
